### ISSUE TITLE
zipfile.open(..., "rU") does not work with Python 3.6

### ISSUE THREAD

**Issue by hroncok** [fedora-java/javapackages#33]
We are trying to build javapackages-tools with Python 3.6, but it fails with:

```
======================================================================
FAIL: test_basic_jar (osgi_prov_test.TestOSGiProv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/javapackages-4.7.0/test/test_common.py", line 165, in test_decorated
    fun(self, stdout, stderr, return_value)
  File "/builddir/build/BUILD/javapackages-4.7.0/test/osgi_prov_test.py", line 22, in test_basic_jar
    self.assertEqual(return_value, 0, stderr)
AssertionError: 1 != 0 : [INFO osgi.prov] input: ['/builddir/build/BUILD/javapackages-4.7.0/test/data/osgi/basic_jar/buildroot/usr/lib/basic.jar']
Traceback (most recent call last):
  File "/builddir/build/BUILD/javapackages-4.7.0/test/../depgenerators/osgi.prov", line 77, in <module>
    builder = TagBuilder()
  File "/builddir/build/BUILD/javapackages-4.7.0/test/../depgenerators/osgi.prov", line 50, in __init__
    cache = OSGiCache(rpmconf)
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/cache/osgi.py", line 52, in __init__
    self._cache = self._process_buildroot()
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/cache/osgi.py", line 78, in _process_buildroot
    bundle = OSGiBundle.from_manifest(path)
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/common/osgi.py", line 132, in from_manifest
    manifest = Manifest(path)
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/common/manifest.py", line 48, in __init__
    self._manifest = self._read_manifest()
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/common/manifest.py", line 63, in _read_manifest
    mf = jarfile.open("META-INF/MANIFEST.MF", "rU")
  File "/usr/lib64/python3.6/zipfile.py", line 1327, in open
    raise ValueError('open() requires mode "r" or "w"')
ValueError: open() requires mode "r" or "w"
======================================================================
FAIL: test_basic_jar (osgi_req_test.TestOSGiReq)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/javapackages-4.7.0/test/test_common.py", line 177, in test_decorated
    fun(self, stdout, stderr, return_value)
  File "/builddir/build/BUILD/javapackages-4.7.0/test/osgi_req_test.py", line 16, in test_basic_jar
    self.assertEqual(return_value, 0, stderr)
AssertionError: 1 != 0 : [INFO osgi.req] input: ['/builddir/build/BUILD/javapackages-4.7.0/test/data/osgi/basic_jar/buildroot/usr/lib/basic.jar']
Traceback (most recent call last):
  File "/builddir/build/BUILD/javapackages-4.7.0/test/../depgenerators/osgi.req", line 91, in <module>
    builder = TagBuilder()
  File "/builddir/build/BUILD/javapackages-4.7.0/test/../depgenerators/osgi.req", line 51, in __init__
    cache = OSGiCache(rpmconf)
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/cache/osgi.py", line 52, in __init__
    self._cache = self._process_buildroot()
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/cache/osgi.py", line 78, in _process_buildroot
    bundle = OSGiBundle.from_manifest(path)
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/common/osgi.py", line 132, in from_manifest
    manifest = Manifest(path)
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/common/manifest.py", line 48, in __init__
    self._manifest = self._read_manifest()
  File "/builddir/build/BUILD/javapackages-4.7.0/python/javapackages/common/manifest.py", line 63, in _read_manifest
    mf = jarfile.open("META-INF/MANIFEST.MF", "rU")
  File "/usr/lib64/python3.6/zipfile.py", line 1327, in open
    raise ValueError('open() requires mode "r" or "w"')
ValueError: open() requires mode "r" or "w"
----------------------------------------------------------------------
XML: /builddir/build/BUILD/javapackages-4.7.0/test/nosetests.xml
----------------------------------------------------------------------
Ran 397 tests in 55.810s
FAILED (failures=2)
```

See https://koji.fedoraproject.org/koji/taskinfo?taskID=16973542

The problem is here: https://github.com/fedora-java/javapackages/blob/4.6.0/python/javapackages/common/manifest.py#L63

The [documentation](https://docs.python.org/3.5/library/zipfile.html#zipfile.ZipFile.open) says:

> *Deprecated since version 3.4, will be removed in version 3.6:* The `'U'` or `'rU'` mode. Use [io.TextIOWrapper](https://docs.python.org/3.5/library/io.html#io.TextIOWrapper) for reading compressed text files in [universal newlines](https://docs.python.org/3.5/glossary.html#term-universal-newlines) mode.

Do you have free cycles for a quick fix? Thanks

**Comment by hroncok** [comment]
Thanks @mizdebsk. Please let me know whether I shall patch the package in Fedora or if this will get there via a release or something else.

**Comment by mizdebsk** [comment]
> Thanks @mizdebsk. Please let me know whether I shall patch the package in Fedora or if this will get there via a release or something else.

Already patched, build running: https://koji.fedoraproject.org/koji/taskinfo?taskID=16989714

**Comment by hroncok** [comment]
:100: :+1:
